py_library(
  name = "adversarial_hinge",
  srcs = ["adversarial_hinge.py"],
  srcs_version = "PY3"
)

py_test(
  name = "adversarial_hinge_test",
  srcs = ["adversarial_hinge_test.py"],
  python_version = "PY3",
  srcs_version = "PY3",
  deps = [
    ":adversarial_hinge",
  ]
)
